CountryAT: Австрия
CountryBE: Белгия
CountryBG: България
CountryCY: Кипър
CountryCZ: Чешка република
CountryDE: Германия
CountryDK: Дания
CountryEE: Естония
CountryEL: Гърция
CountryES: Испания
CountryFI: Финландия
CountryFR: Франция
CountryHR: Хърватия
CountryHU: Унгария
CountryIE: Ирландия
CountryIT: Италия
CountryLT: Литва
CountryLU: Люксембург
CountryLV: Латвия
CountryMT: Малта
CountryNL: Нидерландия
CountryPL: Полша
CountryPT: Португалия
CountryRO: Румъния
CountrySE: Швеция
CountrySI: Словения
CountrySK: Словакия
CountryUK: Обединено кралство
