CountryAT: Rakousko
CountryBE: Belgie
CountryBG: Bulharsko
CountryCY: Kypr
CountryCZ: Česká republika
CountryDE: Německo
CountryDK: Dánsko
CountryEE: Estonsko
CountryEL: Řecko
CountryES: Španělsko
CountryFI: Finsko
CountryFR: Francie
CountryHR: Chorvatsko
CountryHU: Maďarsko
CountryIE: Irsko
CountryIT: Itálie
CountryLT: Litva
CountryLU: Lucembursko
CountryLV: Lotyšsko
CountryMT: Malta
CountryNL: Nizozemsko
CountryPL: Polsko
CountryPT: Portugalsko
CountryRO: Rumunsko
CountrySE: Švédsko
CountrySI: Slovinsko
CountrySK: Slovensko
CountryUK: Spojené království
