CountryAT: Österreich
CountryBE: Belgien
CountryBG: Bulgarien
CountryCY: Zypern
CountryCZ: Tschechische Republik
CountryDE: Deutschland
CountryDK: Dänemark
CountryEE: Estland
CountryEL: Griechenland
CountryES: Spanien
CountryFI: Finnland
CountryFR: Frankreich
CountryHR: Kroatien
CountryHU: Ungarn
CountryIE: Irland
CountryIT: Italien
CountryLT: Litauen
CountryLU: Luxemburg
CountryLV: Lettland
CountryMT: Malta
CountryNL: Niederlande
CountryPL: Polen
CountryPT: Portugal
CountryRO: Rumänien
CountrySE: Schweden
CountrySI: Slowenien
CountrySK: Slowakei
CountryUK: Vereinigtes Königreich
