CountryAT: Αυστρία
CountryBE: Βέλγιο
CountryBG: Βουλγαρία
CountryCY: Κύπρος
CountryCZ: Τσεχική Δημοκρατία
CountryDE: Γερμανία
CountryDK: Δανία
CountryEE: Εσθονία
CountryEL: Ελλάδα
CountryES: Ισπανία
CountryFI: Φινλανδία
CountryFR: Γαλλία
CountryHR: Κροατία
CountryHU: Ουγγαρία
CountryIE: Ιρλανδία
CountryIT: Ιταλία
CountryLT: Λιθουανία
CountryLU: Λουξεμβούργο
CountryLV: Λετονία
CountryMT: Μάλτα
CountryNL: Κάτω Χώρες
CountryPL: Πολωνία
CountryPT: Πορτογαλία
CountryRO: Ρουμανία
CountrySE: Σουηδία
CountrySI: Σλοβενία
CountrySK: Σλοβακία
CountryUK: Ηνωμένο Βασίλειο
