Empty:

SiteTitle: Citizens' Initiatives

About: About

HomeIntro: A citizens' initiative is an officially recognized petition for citizens to demand the attention of their representatives on a specific problem. Below is the list of the ongoing European Citizens' Initiatives (ECI). Each one that collects over one million signatures in the allotted time will be examined by the European Commission.

Annex: Annex
DaysLeft i@Int: #{show i} day#{plural i "" "s"} left
Documents: Documents
DraftLegalAct: Draft legal act
Links: Links
Objectives: Objectives
OtherLanguages: Other languages
ReadMore: Read more
Signatures: Signatures
SignaturesCollected i@Int: #{show i} signatures collected
SignaturesExplanation: To be validated, the initiative must collect a total of more than one million signatures, and reach the signatures quota in at least 7 countries.
SignaturesTable: Signatures by country
SignOnline: Sign online
SignOnlineNotReady: The online collection system of this initiative is not ready yet.
SocialLinks: Social networks
Subject: Subject
Website: Website

CountryCode: Code
CountryName: Name
Today: Today
Total: Total
Target: Target
TargetPercentage: % of target
Web: Web
Paper: Paper
Quota: Quota
QuotaPercentage: % of quota

QuotaExplanation: The quota needs to be reached in at least 7 countries for the initiative to be validated.

# Countries
CountryAT: Austria
CountryBE: Belgium
CountryBG: Bulgaria
CountryCY: Cyprus
CountryCZ: Czech Republic
CountryDE: Germany
CountryDK: Denmark
CountryEE: Estonia
CountryEL: Greece
CountryES: Spain
CountryFI: Finland
CountryFR: France
CountryHR: Croatia
CountryHU: Hungary
CountryIE: Ireland
CountryIT: Italy
CountryLT: Lithuania
CountryLU: Luxembourg
CountryLV: Latvia
CountryMT: Malta
CountryNL: Netherlands
CountryPL: Poland
CountryPT: Portugal
CountryRO: Romania
CountrySE: Sweden
CountrySI: Slovenia
CountrySK: Slovakia
CountryUK: United Kingdom
