Empty:

SiteTitle: Citizens' Initiatives

About: About

HomeIntro: A citizens' initiative is an officially recognized petition for citizens to demand the attention of their representatives on a specific problem. Below is the list of the ongoing European Citizens' Initiatives (ECI). Each one that collects over one million signatures in the allotted time will be examined by the European Commission.

Annex: Annex
DaysLeft i@Int: #{show i} days left
Documents: Documents
DraftLegalAct: Draft legal act
Links: Links
Objectives: Objectives
OtherLanguages: Other languages
ReadMore: Read more
Signatures: Signatures
SignaturesCollected i@Int: #{show i} signatures collected
SignaturesTable: Signatures by country
SignOnline: Sign online
SignOnlineNotReady: The online collection system of this initiative is not ready yet.
Subject: Subject
Website: Website

CountryCode: Code
CountryName: Name
Today: Today
Total: Total
Target: Target
TargetPercentage: % of target
Web: Web
Paper: Paper
Quota: Quota
QuotaPercentage: % of quota

# Countries
CountryAT: Austria
CountryBE: Belgium
CountryBG: Bulgaria
CountryCY: Cyprus
CountryCZ: Czech Republic
CountryDE: Germany
CountryDK: Denmark
CountryEE: Estonia
CountryEL: Greece
CountryES: Spain
CountryFI: Finland
CountryFR: France
CountryHR: Croatia
CountryHU: Hungary
CountryIE: Ireland
CountryIT: Italy
CountryLT: Lithuania
CountryLU: Luxembourg
CountryLV: Latvia
CountryMT: Malta
CountryNL: Netherlands
CountryPL: Poland
CountryPT: Portugal
CountryRO: Romania
CountrySE: Sweden
CountrySI: Slovenia
CountrySK: Slovakia
CountryUK: United Kingdom
