Empty:

SiteTitle: Citizens' Initiatives

About: About

Annex: Annex
DaysLeft i@Int: #{show i} days left
# DaysLeftTooltip: An initiative lasts 1 year
Deadline: Deadline
Documents: Documents
DraftLegalAct: Draft legal act
HomeIntro: 
Links: Links
Objectives: Objectives
OngoingInitiatives i@Int: There #{plural i "is" "are"} #{show i} ongoing initiative#{plural i "" "s"}.
OtherLanguages: Other languages
ReadMore: Read more
Signatures: Signatures
SignaturesCollected i@Int: #{show i} signatures collected
SignaturesTable: Signatures by country
SignOnline: Sign online
SignOnlineNotReady: The online collection system of this initiative is not ready yet.
Subject: Subject
Website: Website

CountryCode: Code
CountryName: Name
Today: Today
Total: Total
Target: Target
TargetPercentage: % of target
Web: Web
Paper: Paper
Quota: Quota

# Countries
CountryAT: Austria
CountryBE: Belgium
CountryBG: Bulgaria
CountryCY: Cyprus
CountryCZ: Czech Republic
CountryDE: Germany
CountryDK: Denmark
CountryEE: Estonia
CountryEL: Greece
CountryES: Spain
CountryFI: Finland
CountryFR: France
CountryHR: Croatia
CountryHU: Hungary
CountryIE: Ireland
CountryIT: Italy
CountryLT: Lithuania
CountryLU: Luxembourg
CountryLV: Latvia
CountryMT: Malta
CountryNL: Netherlands
CountryPL: Poland
CountryPT: Portugal
CountryRO: Romania
CountrySE: Sweden
CountrySI: Slovenia
CountrySK: Slovakia
CountryUK: United Kingdom
