CountryAT: Austria
CountryBE: Bélgica
CountryBG: Bulgaria
CountryCY: Chipre
CountryCZ: República Checa
CountryDE: Alemania
CountryDK: Dinamarca
CountryEE: Estonia
CountryEL: Grecia
CountryES: España
CountryFI: Finlandia
CountryFR: Francia
CountryHR: Croacia
CountryHU: Hungría
CountryIE: Irlanda
CountryIT: Italia
CountryLT: Lituania
CountryLU: Luxemburgo
CountryLV: Letonia
CountryMT: Malta
CountryNL: Países Bajos
CountryPL: Polonia
CountryPT: Portugal
CountryRO: Rumanía
CountrySE: Suecia
CountrySI: Eslovenia
CountrySK: Eslovaquia
CountryUK: Reino Unido
