Empty:

SiteTitle: Initiatives Citoyennes

About: À propos

HomeIntro: Une initiative citoyenne est un mécanisme officiel, semblable à une pétition, permettant aux citoyens de réclamer l'attention de leurs représentants sur un sujet précis. Ce site répertorie les Initiatives Citoyennes Européennes (ICE) en cours. Chaque ICE recueillant plus d'un million de signatures dans le temps imparti sera examinée par la Commission Européenne.

Annex: Annexe
DaysLeft i: #{show i} jours restants
Documents: Documents
DraftLegalAct: Projet d'acte législatif
Links: Liens
Objectives: Objectifs
OtherLanguages: Autres langues
ReadMore: En savoir plus
Signatures: Signatures
SignaturesCollected i: #{show i} signatures collectées
SignaturesTable: Signatures par pays
SignOnline: Signer en ligne
SignOnlineNotReady: Le système de collecte en ligne de cette initiative n'est pas encore prêt.
SocialLinks: Réseaux sociaux
Subject: Objet
Website: Site web

CountryCode: Code
CountryName: Nom
Today: Aujourd'hui
Total: Total
Target: Objectif
TargetPercentage: % de l'objectif
Web: Web
Paper: Papier
Quota: Quota
QuotaPercentage: % du quota

# Pays
CountryAT: Autriche
CountryBE: Belgique
CountryBG: Bulgarie
CountryCY: Chypre
CountryCZ: République tchèque
CountryDE: Allemagne
CountryDK: Danemark
CountryEE: Estonie
CountryEL: Grèce
CountryES: Espagne
CountryFI: Finlande
CountryFR: France
CountryHR: Croatie
CountryHU: Hongrie
CountryIE: Irlande
CountryIT: Italie
CountryLT: Lituanie
CountryLU: Luxembourg
CountryLV: Lettonie
CountryMT: Malte
CountryNL: Pays-Bas
CountryPL: Pologne
CountryPT: Portugal
CountryRO: Roumanie
CountrySE: Suède
CountrySI: Slovénie
CountrySK: Slovaquie
CountryUK: Royaume-Uni
