Empty:

SiteTitle: Initiatives Citoyennes

About: À propos

Annex: Annexe
DaysLeft i: #{show i} jours restants
# DaysLeftTooltip: Une initiative dure 1 an
Deadline: Date limite
Documents: Documents
DraftLegalAct: Projet d'acte législatif
HomeIntro: 
Links: Liens
Objectives: Objectifs
OngoingInitiatives i: Il y a #{show i} initiative#{plural i "" "s"} en cours.
OtherLanguages: Autres langues
ReadMore: En savoir plus
Signatures: Signatures
SignaturesCollected i: #{show i} signatures collectées
SignaturesTable: Signatures par pays
SignOnline: Signer en ligne
SignOnlineNotReady: Le système de collecte en ligne de cette initiative n'est pas encore prêt.
Subject: Objet
Website: Site web

CountryCode: Code
CountryName: Nom
Today: Aujourd'hui
Total: Total
Target: Objectif
TargetPercentage: % de l'objectif
Web: Web
Paper: Papier
Quota: Quota

# Pays
CountryAT: Autriche
CountryBE: Belgique
CountryBG: Bulgarie
CountryCY: Chypre
CountryCZ: République tchèque
CountryDE: Allemagne
CountryDK: Danemark
CountryEE: Estonie
CountryEL: Grèce
CountryES: Espagne
CountryFI: Finlande
CountryFR: France
CountryHR: Croatie
CountryHU: Hongrie
CountryIE: Irlande
CountryIT: Italie
CountryLT: Lituanie
CountryLU: Luxembourg
CountryLV: Lettonie
CountryMT: Malte
CountryNL: Pays-Bas
CountryPL: Pologne
CountryPT: Portugal
CountryRO: Roumanie
CountrySE: Suède
CountrySI: Slovénie
CountrySK: Slovaquie
CountryUK: Royaume-Uni
