CountryAT: an Ostair
CountryBE: an Bheilg
CountryBG: an Bhulgáir
CountryCY: an Chipir
CountryCZ: Poblacht na Seice
CountryDE: an Ghearmáin
CountryDK: an Danmhairg
CountryEE: an Eastóin
CountryEL: an Ghréig
CountryES: an Spáinn
CountryFI: an Fhionlainn
CountryFR: an Fhrainc
CountryHR: an Chróit
CountryHU: an Ungáir
CountryIE: Éire
CountryIT: an Iodáil
CountryLT: an Liotuáin
CountryLU: Lucsamburg
CountryLV: an Laitvia
CountryMT: Málta
CountryNL: an Ísiltír
CountryPL: an Pholainn
CountryPT: an Phortaingéil
CountryRO: an Rómáin
CountrySE: an tSualainn
CountrySI: an tSlóivéin
CountrySK: an tSlóvaic
CountryUK: an Ríocht Aontaithe
