CountryAT: Ausztria
CountryBE: Belgium
CountryBG: Bulgária
CountryCY: Ciprus
CountryCZ: Cseh Köztársaság
CountryDE: Németország
CountryDK: Dánia
CountryEE: Észtország
CountryEL: Görögország
CountryES: Spanyolország
CountryFI: Finnország
CountryFR: Franciaország
CountryHR: Horvátország
CountryHU: Magyarország
CountryIE: Írország
CountryIT: Olaszország
CountryLT: Litvánia
CountryLU: Luxemburg
CountryLV: Lettország
CountryMT: Málta
CountryNL: Hollandia
CountryPL: Lengyelország
CountryPT: Portugália
CountryRO: Románia
CountrySE: Svédország
CountrySI: Szlovénia
CountrySK: Szlovákia
CountryUK: Egyesült Királyság
