CountryAT: Austria
CountryBE: Belgio
CountryBG: Bulgaria
CountryCY: Cipro
CountryCZ: Repubblica ceca
CountryDE: Germania
CountryDK: Danimarca
CountryEE: Estonia
CountryEL: Grecia
CountryES: Spagna
CountryFI: Finlandia
CountryFR: Francia
CountryHR: Croazia
CountryHU: Ungheria
CountryIE: Irlanda
CountryIT: Italia
CountryLT: Lituania
CountryLU: Lussemburgo
CountryLV: Lettonia
CountryMT: Malta
CountryNL: Paesi Bassi
CountryPL: Polonia
CountryPT: Portogallo
CountryRO: Romania
CountrySE: Svezia
CountrySI: Slovenia
CountrySK: Slovacchia
CountryUK: Regno Unito
