CountryAT: L-Awstrija
CountryBE: Il-Belġju
CountryBG: Il-Bulgarija
CountryCY: Ċipru
CountryCZ: Ir-Repubblika Ċeka
CountryDE: Il-Ġermanja
CountryDK: Il-Danimarka
CountryEE: L-Estonja
CountryEL: Il-Greċja
CountryES: Spanja
CountryFI: Il-Finlandja
CountryFR: Franza
CountryHR: Kroazja
CountryHU: L-Ungerija
CountryIE: L-Irlanda
CountryIT: L-Italja
CountryLT: Il-Litwanja
CountryLU: Il-Lussemburgu
CountryLV: Il-Latvja
CountryMT: Malta
CountryNL: Il-Pajjiżi l-Baxxi
CountryPL: Il-Polonja
CountryPT: Il-Portugall
CountryRO: Ir-Rumanija
CountrySE: L-Isvezja
CountrySI: Is-Slovenja
CountrySK: Is-Slovakja
CountryUK: Ir-Renju Unit
