CountryAT: Áustria
CountryBE: Bélgica
CountryBG: Bulgária
CountryCY: Chipre
CountryCZ: República Checa
CountryDE: Alemanha
CountryDK: Dinamarca
CountryEE: Estónia
CountryEL: Grécia
CountryES: Espanha
CountryFI: Finlândia
CountryFR: França
CountryHR: Croácia
CountryHU: Hungria
CountryIE: Irlanda
CountryIT: Itália
CountryLT: Lituânia
CountryLU: Luxemburgo
CountryLV: Letónia
CountryMT: Malta
CountryNL: Países Baixos
CountryPL: Polónia
CountryPT: Portugal
CountryRO: Roménia
CountrySE: Suécia
CountrySI: Eslovénia
CountrySK: Eslováquia
CountryUK: Reino Unido
