CountryAT: Austria
CountryBE: Belgia
CountryBG: Bulgaria
CountryCY: Cipru
CountryCZ: Republica Cehă
CountryDE: Germania
CountryDK: Danemarca
CountryEE: Estonia
CountryEL: Grecia
CountryES: Spania
CountryFI: Finlanda
CountryFR: Franţa
CountryHR: Croaţia
CountryHU: Ungaria
CountryIE: Irlanda
CountryIT: Italia
CountryLT: Lituania
CountryLU: Luxemburg
CountryLV: Letonia
CountryMT: Malta
CountryNL: Ţările de Jos
CountryPL: Polonia
CountryPT: Portugalia
CountryRO: România
CountrySE: Suedia
CountrySI: Slovenia
CountrySK: Slovacia
CountryUK: Regatul Unit
