CountryAT: Rakúsko
CountryBE: Belgicko
CountryBG: Bulharsko
CountryCY: Cyprus
CountryCZ: Česká republika
CountryDE: Nemecko
CountryDK: Dánsko
CountryEE: Estónsko
CountryEL: Grécko
CountryES: Španielsko
CountryFI: Fínsko
CountryFR: Francúzsko
CountryHR: Chorvátsko
CountryHU: Maďarsko
CountryIE: Írsko
CountryIT: Taliansko
CountryLT: Litva
CountryLU: Luxembursko
CountryLV: Lotyšsko
CountryMT: Malta
CountryNL: Holandsko
CountryPL: Poľsko
CountryPT: Portugalsko
CountryRO: Rumunsko
CountrySE: Švédsko
CountrySI: Slovinsko
CountrySK: Slovensko
CountryUK: Spojené kráľovstvo
