Default: &defaults
  host: "127.0.0.1"
  port: 8841
  approot: "//localhost:8841"

Development:
  <<: *defaults

Testing:
  <<: *defaults

Staging:
  <<: *defaults

Production:
  host: "*"
  approot: "//citizens-initiatives.changaco.net"
  <<: *defaults
